# Generated by Django 3.0.8 on 2021-07-06 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptocurrencies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coin',
            old_name='today_rate_usd',
            new_name='price_usd',
        ),
        migrations.AddField(
            model_name='coin',
            name='asset_id',
            field=models.CharField(default=0, max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coin',
            name='is_crypto',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coin',
            name='volume_1day_usd',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coin',
            name='volume_1hrs_usd',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coin',
            name='volume_1mth_usd',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
