# Generated by Django 3.0.8 on 2021-07-06 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='wallet_id',
        ),
        migrations.AddField(
            model_name='user',
            name='portfolio',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
